#!/bin/bash

#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 00:14:59
#SBATCH --mem-per-cpu=16GB
#SBATCH --gpus-per-node=v100:1
#SBATCH -o /mnt/home/bonal1lCMICH/Documents/inverse_problem/inverse/spline_esn_singlenet/out1.out
#SBATCH -e /mnt/home/bonal1lCMICH/Documents/inverse_problem/inverse/spline_esn_singlenet/err1.err
#SBATCH -J test-inn

source ~/.bashrc
conda activate inverse
module load CUDA/10.1.105
python test.py /mnt/scratch/bonal1lCMICH/inverse/spline_esn_singlenet/results/Feb-17-2022/09-49-49